=== DefectiveRussian/HTML-DAM1/eva/fabricantes.dtd
<!ELEMENT fabricantes (fabricante+)>
<!ELEMENT fabricante (nombre, pais, ciudad, web, email, tfn)>
<!ATTLIST fabricante id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT tfn (#PCDATA)>

=== DefectiveRussian/HTML-DAM1/eva/fabricantes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fabricantes SYSTEM "fabricantes.dtd">
<fabricantes>
	<fabricante id="f00">
		<nombre>Fabrika 120</nombre>
		<pais>Rusia</pais>
		<ciudad>Magnitogorsk</ciudad>
		<web>fab120.ru</web>
		<email>fabrikapochta@mail.ru</email>
		<tfn>71112223333</tfn>
	</fabricante>
	<fabricante id="f01">
		<nombre>General Things</nombre>
		<pais>Estados Unidos</pais>
		<ciudad>Dunkirk</ciudad>
		<web>wemakethings.com</web>
		<email>genstuff@proton.mail</email>
		<tfn>16241112222</tfn>
	</fabricante>
	<fabricante id="f02">
		<nombre>伟大领袖的工厂 (Glorious Leader Factory)</nombre>
		<pais>China</pais>
		<ciudad>连州市 (Lianzhou)</ciudad>
		<web>lianfactory.cn</web>
		<email>lianfactory@qq.com</email>
		<tfn>8613811112222</tfn>
	</fabricante>
</fabricantes>
